### ISSUE TITLE
Change to repo name

### ISSUE THREAD

**Issue by Tejas2805** [actions/first-interaction#19]
Currently,

The comment is shown to come from Github Actions. Is it possible to change it to repo/org name?

![Screen Shot 2020-03-19 at 12 06 14 PM](https://user-images.githubusercontent.com/35946746/77030609-1687b180-69da-11ea-9269-993ceb86be07.png)

**Comment by JohnyP36** [comment]
As far as I know this is not possible. 
Maybe if they change the code you can.

**Comment by ncalteen** [comment]
Hello! Apologies for the delay responding to this issue. Unfortunately unless you change the token input to a personal access token or GitHub App, the default will always use the `github-actions` bot.
