### ISSUE TITLE
"\n" no longer works?

### ISSUE THREAD

**Issue by CExWHamdan** [actions/first-interaction#40]
Looks like using "\n" no longer works and is breaking the markdown.

<img width="797" alt="Screen Shot 2021-04-07 at 4 23 57 PM" src="https://user-images.githubusercontent.com/5796654/113929115-a7842300-97bd-11eb-967f-380d59508525.png">

The markdown for the message:

`# Welcome!\nLooks like this is your first time contributing to the`

**Comment by guillermo-varela** [comment]
YAML folded style seems to work: https://yaml-multiline.info/

**Comment by ncalteen** [comment]
Apologies for the lack of response on this issue! It looks like this has been answered so I will go ahead and close it out, however please feel free to reply back if there's anything that you have questions on!
