### ISSUE TITLE
Workflow is not running

### ISSUE THREAD

**Issue by vishal-iyer** [actions/first-interaction#44]
Hi Team,

We are using the first-interaction github actions workflow in our repository. Since a few hours we are unable to get the workflow to run. It is stuck at "Starting Workflow Run". I tried cancelling and rerunning it but that doesn't help
![image](https://user-images.githubusercontent.com/68851483/118646431-d1d5f100-b7fd-11eb-9b45-f2956e59f832.png)

Kindly help

**Comment by flaxel** [comment]
That's not a problem with the action. There was [an incident](https://www.githubstatus.com/incidents/m16jzl31gnqt) in GitHub that has been resolved and the action should run again.

**Comment by ncalteen** [comment]
Hi All, Closing this issue out as I am cleaning up the repo and this appears to be unrelated to the action itself :)
