### ISSUE TITLE
Feature Request: Add labels to trigerred Issues and PRs

### ISSUE THREAD

**Issue by posquit0** [actions/first-interaction#63]
I wish  `first-interaction` action could add configured labels to Issues or PRs

**Comment by yury1m** [comment]
Gghh

**Comment by shink** [comment]
Me too, this would be a useful feature!

**Comment by ncalteen** [comment]
There's another action in the `actions` org that can do this :) https://github.com/actions/labeler Feel free to check it out!

**Comment by rusackas** [comment]
Sorry to bring up an old/closed issue... but I'm not seeing how to configure the above actions/labeler can be configured to use trigger on a contributor's first PR/Issue.  I found this issue searching around hoping this action somehow supported adding a label.
